name: CodiumAI PR-Agent on Review Request

on:
  pull_request:
    types: [opened]

jobs:
  codium_review:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Run CodiumAI PR-Agent
        uses: Codium-ai/pr-agent@main
        env:
          # Configure the PR-Agent to respond only when a review is requested
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          github_action_config.auto_review: "true"
          github_action_config.auto_describe: "false"
          github_action_config.auto_improve: "false"